// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIA_FINALS_SAKILA_GROUP.Models;

public partial class Country
{
    public short CountryId { get; set; }

    public string Country1 { get; set; }

    public DateTime? LastUpdate { get; set; }

    public virtual ICollection<City> Cities { get; set; } = new List<City>();
}