// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIA_FINALS_SAKILA_GROUP.Models;

public partial class Category
{
    public byte CategoryId { get; set; }

    public string Name { get; set; }

    public DateTime LastUpdate { get; set; }

    public virtual ICollection<FilmCategory> FilmCategories { get; set; } = new List<FilmCategory>();
}